---

- name: Create the Worker run file
  template:
    src: rqworker/run_rqworker.j2
    dest: "{{ worker_run_bin }}"
    owner: "{{ application_user }}"
    group: "{{ application_group }}"
    mode: 0770
    backup: yes
  notify:
    - Enable and restart workers

- name: Create systemd unit for worker
  template: src=rqworker/services/rqworker.service.j2
            dest=/etc/systemd/system/rqworker@.service
            mode=0664
            backup=no
  notify:
    - Reload systemd
    - Enable and restart workers

- name: Disable and stop all workers
  shell: systemctl stop rqworker*.service
  notify:
    - Enable and restart workers
