---

# Workers

worker_count: 2
worker_user: "{{ application_user }}"
worker_group: "{{ application_group }}"

worker_dir: "{{ application_dir }}workers/"
worker_bins_dir: "{{ worker_dir }}bins/"
worker_run_bin: "{{ worker_bins_dir }}run_rqworker.sh"
