version: "3.4"

services:
  db:
    image: postgres:9.6-alpine
    environment:
      POSTGRES_PASSWORD: development
      POSTGRES_USER: development
      POSTGRES_DB: development_db
    ports:
      - "5432:5432"
  redis:
    image: redis:3.2-alpine
    ports:
      - "6379:6379"
  kong:
    build:
      dockerfile: kong.dockerfile
      context: .
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong_db
      KONG_PG_PORT: 5432
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
      KONG_PG_DATABASE: kong
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_CUSTOM_PLUGINS: api-gateway-httplog
    depends_on:
      - kong_db
    ports:
      - "8001:8001"
      - "8000:8000"
  kong_db:
    image: postgres:9.6-alpine
    environment:
      POSTGRES_PASSWORD: kong
      POSTGRES_USER: kong
      POSTGRES_DB: kong
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
    ports:
      - "9200:9200"
    environment:
      - "http.host=0.0.0.0"
      - "transport.host=127.0.0.1"
volumes:
  static: {}
  media: {}
