version: "3.4"

services:
  django:
    build:
      context: .
      args:
        requirements: requirements/local.txt # Use local requirements!
    environment:
      DATABASE_URL: postgres://development:development@db/development_db
      REDIS_HOST: redis
      KONG_ADMIN_URL: http://kong:8001/
    depends_on:
      - db
      - redis
    volumes:
      - ./:/app/code/
    ports:
      - "8080:8080"
  rq_worker: # This is a copy of django service
    build:
      context: .
      args:
        requirements: requirements/local.txt # Use local requirements!
    environment:
      DATABASE_URL: postgres://development:development@db/development_db
      REDIS_HOST: redis
    depends_on:
      - db
      - redis
    volumes:
      - ./:/app/code/
    command: /app/venv/bin/python manage.py rqworker default create_model
  db:
    image: postgres:9.6-alpine
    environment:
      POSTGRES_PASSWORD: development
      POSTGRES_USER: development
      POSTGRES_DB: development_db
  redis:
    image: redis:3.2-alpine
    ports:
      - "6379:6379"
  kong:
    build:
      dockerfile: kong.dockerfile
      context: .
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong_db
      KONG_PG_PORT: 5432
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
      KONG_PG_DATABASE: kong
    depends_on:
      - kong_db
    ports:
      - "8001:8001"
      - "8000:8000"
  kong_db:
    image: postgres:9.6-alpine
    environment:
      POSTGRES_PASSWORD: kong
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      
