site_name: API Gateway
site_url: https://datosgobar.github.io/api-gateway
site_description: Documentación de la API Gateway, la solución de administración de APIs REST de la Administración Pública Nacional de la República Argentina.
site_author: Datos Argentina
repo_url: https://github.com/datosgobar/api-gateway/

nav:
  - Inicio: 'index.md'
  - Usuarios:
    - Comenzar a usar API Gateway: 'users/quick-start.md'
    - Publicar APIs: 'users/publish-apis.md'
    - Compilar documentación: 'users/apis-docs.md'
    - Administrar cuotas: 'users/rate-limiting.md'
    - Administrar usuarios de las APIs: 'users/tokens.md'
    - Recolectar analytics: 'users/analytics.md'
    - Arquitectura de API Gateway: 'architecture.md'
  - Administradores: 'admin.md'
  - Desarrolladores: 'development.md'

theme: datosgobar_docs

markdown_extensions: [fenced_code, codehilite, admonition]

google_analytics: ['UA-91435482-1', "https://datosgobar.github.io/api-gateway"]
