---

- name: create systemd unit files
  template: src=services/gunicorn.service.j2
            dest=/etc/systemd/system/gunicorn.service
            mode=0664
            backup=no

- name: create systemd socket files
  template: src=services/gunicorn.socket.j2
            dest=/etc/systemd/system/gunicorn.socket
            mode=0664
            backup=no
  notify:
    - Reload systemd
    - Enable and restart web server

# This is a bug, I have to restart gunicorn because I cannot detect repo changes.
-  name: trigger gunicorn-restart
   command: /bin/true
   notify:
     - Enable and restart web server
