---

- name: Add backup script
  template: src=bins/postgresql_backup.sh
            dest={{ postgresql_backup_bin }}
            owner={{ application_user }}
            group={{ application_group }}
            mode=0770
            backup=yes

- name: Create systemd backup unit file
  template: src=services/postgresql_backup.service
            dest=/etc/systemd/system/postgresql_backup.service
            mode=0660
            backup=no
  notify: Enable postgresql backup timer

- name: Create systemd backup timer file
  template: src=services/postgresql_backup.timer
            dest=/etc/systemd/system/postgresql_backup.timer
            mode=0660
            backup=no
  notify: Enable postgresql backup timer
