---

#Taken from: https://github.com/ansible/ansible-examples/blob/master/language_features/postgresql.yml
- name: Ensure database is created
  postgresql_db:
    name: "{{ postgresql_database_name }}"
    encoding: UTF-8
    lc_collate: en_US.UTF-8
    lc_ctype: en_US.UTF-8
    template: template0
  become: yes
  become_user: postgres
  vars:
    ansible_ssh_pipelining: true

- name: Ensure user has access to database
  postgresql_user:
    db: "{{ postgresql_database_name }}"
    name: "{{ postgresql_user }}"
    password: "{{ postgresql_password }}"
    priv: ALL
  become: yes
  become_user: postgres
  vars:
    ansible_ssh_pipelining: true

- name: Ensure user does not have unnecessary privilege
  postgresql_user:
    name: "{{ postgresql_user}}"
    role_attr_flags: NOSUPERUSER,NOCREATEDB
  become: yes
  become_user: postgres
  vars:
    ansible_ssh_pipelining: true

- name: ensure no other user can access the database
  postgresql_privs:
    db: "{{ postgresql_database_name }}"
    role: PUBLIC
    type: database
    priv: ALL
    state: absent
  become: yes
  become_user: postgres
  vars:
    ansible_ssh_pipelining: true
