---

- name: Check credentials
  fail:
    msg: "Missing 'postgresql_user' credential variable"
  when: postgresql_user == ""

- name: Check credentials
  fail:
    msg: "Missing 'postgresql_database_name' credential variable"
  when: postgresql_database_name == ""

- name: Check credentials
  fail:
    msg: "Missing 'postgresql_password' credential variable"
  when: postgresql_password == ""

- name: Check credentials
  fail:
    msg: "Missing 'kong_database_name' credential variable"
  when: kong_database_name == ""

- name: Check credentials
  fail:
    msg: "Missing 'kong_user' credential variable"
  when: kong_user == ""

- name: Check credentials
  fail:
    msg: "Missing 'kong_database_pass' credential variable"
  when: kong_database_pass == ""


- include_tasks: dependencies.yml
- include_tasks: configure.yml
- include_tasks: security.yml

# File structures
- name: Create postgresql directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ application_user }}"
    group: postgres
    mode: 0770
  with_items:
    - "{{ postgresql_dir }}"
    - "{{ postgresql_backup_dir }}"
    - "{{ postgresql_bins }}"

- include_tasks: backups.yml
- include_tasks: create_app_database.yml
- include_tasks: create_kong_database.yml

- name: Backup database
  shell: "{{ postgresql_backup_bin }}"
  become_user: "{{ application_user }}"
  tags: quickly

# Systemd unit
- name: Enable postgresql systemd unit
  service:
    state: restarted
    name: postgresql.service
    enabled: yes
