---

- name: Set hard fsize ulimit
  pam_limits:
    domain: www-data
    limit_type: hard
    limit_item: fsize
    value: "{{ fsize_hard_ulimit }}"
    use_max: yes


- name: Set soft fsize ulimit
  pam_limits:
    domain: www-data
    limit_type: soft
    limit_item: fsize
    value: "{{ fsize_soft_ulimit }}"
    use_max: yes

- name: Configure file-max
  sysctl:
    name: fs.file-max
    value: 70000
    state: present

- name: Modify worker_rlimit_nofile
  lineinfile:
    path: /etc/nginx/nginx.conf
    regexp: '^worker_rlimit_nofile'
    insertbefore: '^http {.*'
    line: 'worker_rlimit_nofile {{ nginx_worker_rlimit_nofile }};'

- name: Modify nginx worker connections
  lineinfile:
    path: /etc/nginx/nginx.conf
    regexp: 'worker_connections'
    insertbefore: '^events {.*'
    line: 'worker_connections {{ nginx_worker_connections }};'
