# Generated by Django 2.0.1 on 2018-02-02 15:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True,
                                          validators=[
                                              django.core.validators.RegexValidator('^[0-9a-zA-Z\\.\\_\\~\\\\\\-]+$',
                                                                                    'Only alphanumeric and . - _ ~ characters are allowed.')])),
                ('upstream_url', models.URLField()),
                ('uris', models.CharField(max_length=200,
                                         validators=[
                                             django.core.validators.RegexValidator('^([/]{1}[\\w\\d]+)*\\/?$',
                                                                                   'Only alphanumeric and _ characters are allowed. \nMust be prefixed with slash (/)')])),
                ('enabled', models.BooleanField()),
                ('kong_id', models.CharField(max_length=100, null=True)),
                ('strip_uri', models.BooleanField(default=True)),
            ],
        ),
    ]
