# Generated by Django 2.0.1 on 2018-02-15 13:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_registry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apidata',
            name='hosts',
            field=models.CharField(blank=True, default='', max_length=200, validators=[django.core.validators.RegexValidator('^(?!:\\/\\/)([a-zA-Z0-9-_]+\\.)*[a-zA-Z0-9][a-zA-Z0-9-_]+\\.[a-zA-Z]{2,11}?$', 'Only domain names are allowed')]),
        ),
        migrations.AlterField(
            model_name='apidata',
            name='uris',
            field=models.CharField(blank=True, default='', max_length=200, validators=[django.core.validators.RegexValidator('^\\s*(([/]{1}[\\w\\d]+)*\\/?)(,\\s*(([/]{1}[\\w\\d]+)*\\/?))*\\s*$', 'Only alphanumeric and _ characters are allowed. \nMust be prefixed with slash (/)')]),
        ),
    ]
