# Generated by Django 2.0.1 on 2018-02-05 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_registry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='kong_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
