# Generated by Django 2.0.1 on 2018-02-05 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_registry', '0002_api_kong_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='strip_uri',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
