# Generated by Django 2.0.1 on 2018-02-15 17:03

import api_management.apps.api_registry.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_registry', '0002_auto_20180215_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apidata',
            name='hosts',
            field=models.CharField(blank=True, default='', max_length=200, validators=[api_management.apps.api_registry.validators.HostsValidator()]),
        ),
        migrations.AlterField(
            model_name='apidata',
            name='name',
            field=models.CharField(max_length=200, unique=True, validators=[api_management.apps.api_registry.validators.AlphanumericValidator()]),
        ),
        migrations.AlterField(
            model_name='apidata',
            name='uris',
            field=models.CharField(blank=True, default='', max_length=200, validators=[api_management.apps.api_registry.validators.UrisValidator()]),
        ),
    ]
