# Generated by Django 2.0.1 on 2018-04-23 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_registry', '0002_auto_20180420_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='jwtcredential',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
    ]
