# Generated by Django 2.0.1 on 2018-02-05 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_registry', '0003_api_strip_uri'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='strip_uri',
            field=models.BooleanField(default=True),
        ),
    ]
