# Generated by Django 2.0.1 on 2018-04-23 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_registry', '0003_jwtcredential_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='KongPluginAcl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('kong_id', models.UUIDField(null=True)),
                ('apidata', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api_registry.KongApi')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
