# Generated by Django 2.0.1 on 2018-02-23 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_registry', '0003_apidata_preserve_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='apidata',
            name='documentation_url',
            field=models.URLField(blank=True),
        ),
    ]
