# Generated by Django 2.0.1 on 2018-02-26 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_registry', '0004_apidata_documentation_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apidata',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
    ]
