# Generated by Django 2.0.1 on 2018-02-07 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_registry', '0004_auto_20180205_1534'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Api',
            new_name='ApiData',
        ),
    ]
