# Generated by Django 2.0.1 on 2018-04-27 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_registry', '0004_kongpluginacl'),
    ]

    operations = [
        migrations.AddField(
            model_name='kongapi',
            name='use_swagger',
            field=models.BooleanField(default=True),
        ),
    ]
