# Generated by Django 2.0.1 on 2018-03-06 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_registry', '0005_auto_20180228_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='apidata',
            name='rate_limiting_day',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='apidata',
            name='rate_limiting_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='apidata',
            name='rate_limiting_hour',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='apidata',
            name='rate_limiting_minute',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='apidata',
            name='rate_limiting_second',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
