# Generated by Django 2.0.1 on 2018-05-02 14:28
from django.db.utils import IntegrityError
from django.db import migrations, transaction


def init_missing_acl(apps, _):

    KongApi = apps.get_model('api_registry', 'KongApi')
    KongPluginAcl = apps.get_model('api_registry', 'KongPluginAcl')

    for kongapi in KongApi.objects.filter(kongpluginacl=None):
        KongPluginAcl(apidata=kongapi).save()
    

class Migration(migrations.Migration):

    dependencies = [
        ('api_registry', '0005_kongapi_use_swagger'),
    ]

    operations = [
        migrations.RunPython(init_missing_acl),
    ]
