# Generated by Django 2.0.1 on 2018-06-08 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_registry', '0006_acl_data_migration'),
    ]

    operations = [
        migrations.CreateModel(
            name='KongPluginCors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('kong_id', models.UUIDField(null=True)),
                ('origins', models.CharField(default='*', max_length=255)),
                ('apidata', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api_registry.KongApi')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
