# Generated by Django 2.0.1 on 2018-03-06 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_registry', '0006_auto_20180306_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='apidata',
            name='rate_limiting_kong_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='apidata',
            name='rate_limiting_day',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='apidata',
            name='rate_limiting_hour',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='apidata',
            name='rate_limiting_minute',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='apidata',
            name='rate_limiting_second',
            field=models.IntegerField(default=0),
        ),
    ]
