# Generated by Django 2.0.1 on 2018-06-11 14:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_registry', '0006_acl_data_migration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kongpluginacl',
            old_name='apidata',
            new_name='parent',
        ),
        migrations.RenameField(
            model_name='kongpluginhttplog',
            old_name='apidata',
            new_name='parent',
        ),
        migrations.RenameField(
            model_name='kongpluginjwt',
            old_name='apidata',
            new_name='parent',
        ),
        migrations.RenameField(
            model_name='kongpluginratelimiting',
            old_name='apidata',
            new_name='parent',
        ),
        migrations.RenameModel(
            old_name='KongPluginRateLimiting',
            new_name='KongApiPluginRateLimiting',
        ),
        migrations.RenameModel(
            old_name='KongPluginAcl',
            new_name='KongApiPluginAcl',
        ),
        migrations.RenameModel(
            old_name='KongPluginHttpLog',
            new_name='KongApiPluginHttpLog',
        ),
        migrations.RenameModel(
            old_name='KongPluginJwt',
            new_name='KongApiPluginJwt',
        ),
        migrations.CreateModel(
            name='KongConsumerPluginRateLimiting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('kong_id', models.UUIDField(null=True)),
                ('second', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('minute', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('hour', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('day', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('parent',
                 models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api_registry.KongConsumer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
