# Generated by Django 2.0.1 on 2018-06-11 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_registry', '0006_acl_data_migration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kongpluginacl',
            old_name='apidata',
            new_name='parent',
        ),
        migrations.RenameField(
            model_name='kongpluginhttplog',
            old_name='apidata',
            new_name='parent',
        ),
        migrations.RenameField(
            model_name='kongpluginjwt',
            old_name='apidata',
            new_name='parent',
        ),
        migrations.RenameField(
            model_name='kongpluginratelimiting',
            old_name='apidata',
            new_name='parent',
        ),
    ]
