# Generated by Django 2.0.1 on 2018-03-07 18:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_registry', '0007_auto_20180306_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apidata',
            name='rate_limiting_day',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='apidata',
            name='rate_limiting_hour',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='apidata',
            name='rate_limiting_minute',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='apidata',
            name='rate_limiting_second',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
