# Generated by Django 2.0.1 on 2018-06-11 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_registry', '0008_auto_20180611_1115'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='KongPluginAcl',
            new_name='KongApiPluginAcl',
        ),
        migrations.RenameModel(
            old_name='KongPluginHttpLog',
            new_name='KongApiPluginHttpLog',
        ),
        migrations.RenameModel(
            old_name='KongPluginJwt',
            new_name='KongApiPluginJwt',
        ),
    ]
