# Generated by Django 2.0.1 on 2018-03-13 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_registry', '0008_auto_20180307_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='apidata',
            name='httplog2_api_key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='apidata',
            name='httplog2_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
