# Generated by Django 2.0.1 on 2018-06-11 14:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_registry', '0009_auto_20180611_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='KongConsumerPluginRateLimiting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('kong_id', models.UUIDField(null=True)),
                ('second', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('minute', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('hour', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('day', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('parent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api_registry.KongConsumer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
