# Generated by Django 2.0.1 on 2018-06-15 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_registry', '0009_merge_cors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kongapipluginjwt',
            name='anonymous_consumer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api_registry.KongConsumer'),
        ),
    ]
