# Generated by Django 2.0.1 on 2018-03-13 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_registry', '0009_auto_20180313_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='apidata',
            name='httplog2_kong_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
