# Generated by Django 2.0.1 on 2018-03-13 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_registry', '0010_apidata_httplog2_kong_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='apidata',
            name='httplog2_endpoint',
            field=models.URLField(blank=True),
        ),
    ]
