# Generated by Django 2.0.1 on 2018-03-14 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_registry', '0011_apidata_httplog2_endpoint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apidata',
            name='httplog2_endpoint',
        ),
    ]
