# Generated by Django 2.0.1 on 2018-10-16 18:02

import api_management.apps.api_registry.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_registry', '0012_auto_20180821_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='RootKongApi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('kong_id', models.UUIDField(null=True)),
                ('upstream_url', models.URLField()),
                ('hosts', models.CharField(max_length=200,
                                           validators=[api_management.apps.api_registry.validators.HostsValidator()])),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
