# Generated by Django 2.0.1 on 2018-04-03 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_registry', '0012_remove_apidata_httplog2_endpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='apidata',
            name='httplog2_ga_exclude_regex',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
