# Generated by Django 2.0.1 on 2018-11-09 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_registry', '0013_rootkongapi'),
    ]

    operations = [
        migrations.AddField(
            model_name='kongapipluginratelimiting',
            name='policy',
            field=models.CharField(choices=[('local', 'local'), ('cluster', 'cluster')], default='local', max_length=12),
        ),
        migrations.AddField(
            model_name='kongconsumerpluginratelimiting',
            name='policy',
            field=models.CharField(choices=[('local', 'local'), ('cluster', 'cluster')], default='local', max_length=12),
        ),
    ]
