# Generated by Django 2.0.1 on 2018-04-12 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_registry', '0014_tokenrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenrequest',
            name='api',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_registry.ApiData'),
            preserve_default=False,
        ),
    ]
