# Generated by Django 2.0.1 on 2019-01-15 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_registry', '0014_auto_20181109_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='KongApiHistoricHits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accumulated_hits', models.IntegerField(default=0)),
                ('kong_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api_registry.KongApi')),
            ],
        ),
    ]
