# Generated by Django 2.0.1 on 2018-04-13 15:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_registry', '0016_tokenrequest_api'),
    ]

    operations = [
        migrations.CreateModel(
            name='HttpLogData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kong_id', models.UUIDField(null=True)),
                ('api_key', models.CharField(max_length=100)),
                ('exclude_regex', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JwtData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kong_id', models.UUIDField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RateLimitingData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kong_id', models.UUIDField(null=True)),
                ('second', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('minute', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('hour', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('day', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='apidata',
            name='httplog2_api_key',
        ),
        migrations.RemoveField(
            model_name='apidata',
            name='httplog2_enabled',
        ),
        migrations.RemoveField(
            model_name='apidata',
            name='httplog2_ga_exclude_regex',
        ),
        migrations.RemoveField(
            model_name='apidata',
            name='httplog2_kong_id',
        ),
        migrations.RemoveField(
            model_name='apidata',
            name='jwt_enabled',
        ),
        migrations.RemoveField(
            model_name='apidata',
            name='jwt_kong_id',
        ),
        migrations.RemoveField(
            model_name='apidata',
            name='rate_limiting_day',
        ),
        migrations.RemoveField(
            model_name='apidata',
            name='rate_limiting_enabled',
        ),
        migrations.RemoveField(
            model_name='apidata',
            name='rate_limiting_hour',
        ),
        migrations.RemoveField(
            model_name='apidata',
            name='rate_limiting_kong_id',
        ),
        migrations.RemoveField(
            model_name='apidata',
            name='rate_limiting_minute',
        ),
        migrations.RemoveField(
            model_name='apidata',
            name='rate_limiting_second',
        ),
        migrations.AddField(
            model_name='ratelimitingdata',
            name='apidata',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api_registry.ApiData'),
        ),
        migrations.AddField(
            model_name='jwtdata',
            name='apidata',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api_registry.ApiData'),
        ),
        migrations.AddField(
            model_name='httplogdata',
            name='apidata',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api_registry.ApiData'),
        ),
    ]
