# Generated by Django 2.0.1 on 2018-04-16 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_registry', '0018_auto_20180416_1113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apidata',
            old_name='uris',
            new_name='uri',
        ),
        migrations.AddField(
            model_name='apidata',
            name='docs_kong_id',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='httplogdata',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jwtdata',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ratelimitingdata',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='apidata',
            name='kong_id',
            field=models.UUIDField(null=True),
        ),
        migrations.AlterField(
            model_name='httplogdata',
            name='kong_id',
            field=models.UUIDField(null=True),
        ),
        migrations.AlterField(
            model_name='jwtdata',
            name='kong_id',
            field=models.UUIDField(null=True),
        ),
        migrations.AlterField(
            model_name='ratelimitingdata',
            name='kong_id',
            field=models.UUIDField(null=True),
        ),
    ]
