---

- name: Check credentials
  fail:
    msg: "Missing 'kong_database_name' credential variable"
  when: kong_database_name == ""

- name: Check credentials
  fail:
    msg: "Missing 'kong_user' credential variable"
  when: kong_user == ""

- name: Check credentials
  fail:
    msg: "Missing 'kong_database_pass' credential variable"
  when: kong_database_pass == ""

- name: Copy default configuration
  copy:
    src: /etc/kong/kong.conf.default
    dest: /etc/kong/kong.conf
    remote_src: yes
    force: no

- name: Increase ulimit
  pam_limits:
    domain: kong
    limit_type: soft
    limit_item: nofile
    value: 4096

- name: Configure ulimit file
  pam_limits:
    domain: "*"
    limit_type: soft
    limit_item: nofile
    value: 4096

- name: Create prefix directory
  file:
    path: "{{ kong_prefix }}"
    state: directory
    recurse: yes

- name: Configure PostgreSQL access host
  lineinfile:
    path: /etc/kong/kong.conf
    regexp: '^(#)?pg_host = .*'
    line: 'pg_host = {{ kong_database_host }}'

- name: Configure PostgreSQL access user
  lineinfile:
    path: /etc/kong/kong.conf
    regexp: '^(#)?pg_user = .*'
    line: 'pg_user = {{ kong_user }}'

- name: Configure PostgreSQL access password
  lineinfile:
    path: /etc/kong/kong.conf
    regexp: '^(#)?pg_password = .*'
    line: 'pg_password = {{ kong_database_pass }}'

- name: Configure PostgreSQL access database name
  lineinfile:
    path: /etc/kong/kong.conf
    regexp: '^(#)?pg_database = .*'
    line: 'pg_database = {{ kong_database_name }}'


- name: Configure prefix
  lineinfile:
    path: /etc/kong/kong.conf
    regexp: '^(#)?prefix = .*'
    line: 'prefix = {{ kong_prefix }}'

- name: Configure kong Port
  lineinfile:
    path: /etc/kong/kong.conf
    regexp: '^(#)?proxy_listen = .*'
    line: 'proxy_listen = {{ kong_proxy_listen }}'

- name: Configure kong admin listen
  lineinfile:
    path: /etc/kong/kong.conf
    regexp: '^(#)?admin_listen = .*'
    line: 'admin_listen = {{ kong_admin_listen }}'

- name: Run kong migrations
  shell: kong migrations up

- name: Run kong
  shell: kong restart
