---


- name: Install Datadog dependencies
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - apt-transport-https

- name: Add datadog repository
  apt_repository:
    repo: deb https://apt.datadoghq.com/ stable main
    state: present


- name: Add datadog apt key
  apt_key:
    id: C7A7DA52
    keyserver: hkp://keyserver.ubuntu.com:80
    state: present


- name: Install datadog
  apt:
    name: datadog-agent
    state: present
    update_cache: yes


- name: Configure datadog
  copy:
    src: /etc/dd-agent/datadog.conf.example
    dest: /etc/dd-agent/datadog.conf
    remote_src: yes
    force: no

- name: Configure kong integration
  copy:
    src: /etc/dd-agent/conf.d/kong.yaml.example
    dest: /etc/dd-agent/conf.d/kong.yaml
    remote_src: yes
    force: no


- name: Configure API key
  lineinfile:
    path: /etc/dd-agent/datadog.conf
    regexp: '^api_key:.*'
    line: 'api_key: {{ kong_datadog_api_key }}'


- name: Restart datadog
  systemd:
    name: datadog-agent.service
    state: restarted
    daemon_reload: yes
