---


- name: Setup http-log
  uri:
    url: "http://{{ kong_admin_listen }}/apis/{{ item.name }}/plugins/"
    method: PUT
    body: "name=http-log&config.method=POST&config.http_endpoint={{ item.upstream_url }}/{{ analytics_endpoint }}"
    status_code: 200,201
  with_items: "{{ kong_api_map }}"
