---


- name: Copy HTTP log 2 plugin
  copy:
    src: httplog2-kong # from roles/kong/files/httplog2-kong
    dest: "{{ application_utils_dir }}"
    owner: "{{ application_user }}"
    group: "{{ application_group }}"
    directory_mode: 0770

- name: Install json-lua
  shell: luarocks install json-lua

- name: Make lua plugin
  shell: "luarocks make"
  args:
    chdir: "{{ httplog2_plugin_dir }}"

- name: Configure httplog2 plugin
  lineinfile:
    path: /etc/kong/kong.conf
    regexp: '^(#)?custom_plugins = .*'
    line: 'custom_plugins = httplog2'
