---

- include_tasks: dependencies.yml

# Configure psql
- include_tasks: psql.yml
- include_tasks: datadog.yml
  when: kong_datadog_api_key is defined

- include_tasks: configure.yml

- include_tasks: apis/main.yml

- include_tasks: apis/datadog.yml
  when: kong_datadog_api_key is defined

- include_tasks: apis/rate_limit.yml
  when: use_rate_limit

- include_tasks: security.yml

- include_tasks: http_log.yml

- include_tasks: configure_logrotate.yml
