---

- name: Check if kong-community-edition is installed
  command: dpkg-query -s kong-community-edition
  ignore_errors: yes
  changed_when: False
  register: kong_check

- name: Install Kong dependencies
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - openssl
    - libpcre3
    - procps
    - perl
  when: kong_check|failed

- name: Install kong
  apt:
    deb: "{{ kong_download_deb }}"
  when: kong_check|failed

- name: Copy default configuration
  copy:
    src: /etc/kong/kong.conf.default
    dest: /etc/kong/kong.conf
    remote_src: yes
    force: no

# Configure psql
- include_tasks: datadog.yml
  when: kong_datadog_api_key is defined

- include_tasks: install_http_log2.yml
- include_tasks: configure.yml

- include_tasks: apis/main.yml

- include_tasks: apis/datadog.yml
  when: kong_datadog_api_key is defined

- include_tasks: apis/rate_limit.yml
  when: use_rate_limit

- include_tasks: security.yml

- include_tasks: http_log.yml
- include_tasks: http_log2.yml
