---


- name: Install PostgreSQL as Kong dependency
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - postgresql
    - postgresql-contrib
    - python-psycopg2 # For ansible postgresql module

- name: Install Kong dependencies
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - openssl
    - libpcre3
    - procps
    - perl

- name: Configure ulimit file
  pam_limits:
    domain: "*"
    limit_type: soft
    limit_item: nofile
    value: 4096

- name: Install kong
  apt:
    deb: "{{ kong_download_deb }}"

# Configure psql
- include_tasks: psql.yml
- include_tasks: datadog.yml
  when: kong_datadog_api_key is defined

- include_tasks: install_http_log2.yml
- include_tasks: configure.yml

- include_tasks: apis/main.yml

- include_tasks: apis/datadog.yml
  when: kong_datadog_api_key is defined

- include_tasks: apis/rate_limit.yml
  when: use_rate_limit

- include_tasks: security.yml

- include_tasks: http_log.yml
