---

- name: Allow server ports
  ufw:
    rule: allow
    port: "{{ item }}"
  with_items:
    - "{{ kong_port }}"

- name: Allow server ports
  ufw:
    port: "{{ kong_admin_port }}"
    rule: allow
    src: "{{ item }}"
    proto: tcp
  with_items:
    - 10.0.0.0/8
    - 172.16.0.0/12
    - 192.168.0.0/16