---

application_bins_dir: "{{ application_dir }}bins/"
application_conf_dir: "{{ application_dir }}conf/"
application_virtualenv_dir: "{{ application_dir }}venv/"
application_virtualenv_activate: "{{ application_virtualenv_dir }}bin/activate"
application_media_dir: "{{ application_dir }}media/"
application_static_dir: "{{ application_dir }}static/"
