---

- name: Install tools
  apt: name={{item}} state=present update_cache=yes
  with_items:
    - htop
    - vim
    - socat # UDP connection debugging
    - jq
    - unzip
    - acl # required for running ansible unprivileged user tasks
