---

- name: Create application group
  group:
    name: "{{ application_group }}"
    state: present

- name: Create application user
  user:
    name: "{{ application_user }}"
    comment: "Devartis Application user"
    group: "{{ application_group }}"
    home: "{{ application_ansible_user_home }}"
    generate_ssh_key: "{{ common_generate_ssh_key }}"

- name: Create utils directory
  file:
    path: "{{ application_utils_dir }}"
    mode: 0770
    owner: "{{ application_user }}"
    group: "{{ application_group }}"
    state: directory
