---

- name: Create application group
  group:
    name: "{{ application_group }}"
    state: present

- name: Create application user
  user:
    name: "{{ application_user }}"
    comment: "Devartis Application user"
    append: yes
    groups: "{{ application_group }}"
    home: "{{ application_user_home }}"

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ application_user }}"
    group: "{{ application_group }}"
  with_items:
    - "{{ application_utils_dir }}"
