---


- name: Add datadog plugin API
  uri:
    url: "http://{{ kong_admin_listen }}/apis/{{ item.name }}/plugins/"
    method: POST
    body: "name=datadog"
    status_code: 201
  with_items: "{{ kong_api_map }}"

