---

- name: Ensure API names available
  uri:
    url: "http://{{ kong_admin_listen }}/apis/{{ item.name }}"
    method: DELETE
    status_code: 204,404
  with_items: "{{ kong_api_map }}"

- name: Add API
  uri:
    url: "http://{{ kong_admin_listen }}/apis/"
    method: PUT
    body: "name={{ item.name }}&hosts={{ item.hosts }}&upstream_url={{ item.upstream_url }}&upstream_connect_timeout=10000&upstream_send_timeout=10000&upstream_read_timeout=10000&preserve_host={{ item.preserve_host|default(true) }}"
    status_code: 201,200
  with_items: "{{ kong_api_map }}"


- name: Enable CORS
  uri:
    url: "http://{{ kong_admin_listen }}/apis/{{ item.name }}/plugins/"
    method: POST
    body: "name=cors&config.origins=*"
    status_code: 201
  with_items: "{{ kong_api_map }}"
  when: item.use_cors | default(false)


