---

application_clone_url: git@github.com:datosgobar/api-gateway.git
application_deploy_ssh_key_required: no # Usar 'application_deploy_ssh_key' con el valor de la api key privada!
database_url: psql://database_user:database_password@127.0.0.1:5432/database_name
allowed_host: 192.168.35.5
nginx_media_dir: "{{ application_dir }}media/"
nginx_static_dir: "{{ application_dir }}static/"
