---

- name: Install dependencies
  apt:
    name: "{{item}}"
    state: present
    update_cache: yes
  with_items:
    - python3
    - python3-pip
    - python3-venv
    - python3-dev
    - python3-pillow
    - python3-virtualenv
    - python-virtualenv # Required by ansible's pip module

- name: Install virtualenv via pip
  pip:
    name: virtualenv
    executable: pip3
    virtualenv_python: python3
