---

#GUNICORN
gunicorn_bin: "{{ application_virtualenv_dir }}bin/gunicorn"

gunicorn_dir: "{{ application_dir }}gunicorn/"
gunicorn_socket_dir: "{{ gunicorn_dir }}sockets/"
gunicorn_log_dir: "{{ gunicorn_dir }}logs/"
gunicorn_conf_dir: "{{ gunicorn_dir }}config/"
gunicorn_bins_dir: "{{ gunicorn_dir }}bins/"

gunicorn_socket: "{{ gunicorn_socket_dir }}gunicorn.sock"
gunicorn_pid: "{{ gunicorn_socket_dir }}gunicorn.pid"


gunicorn_access_log: "{{ gunicorn_log_dir }}access.log"
gunicorn_error_log: "{{ gunicorn_log_dir }}error.log"

gunicorn_conf: "{{ gunicorn_conf_dir }}config.py"

run_gunicorn_bin: "{{ gunicorn_bins_dir }}run_gunicorn.sh"

gunicorn_user: "{{ application_user }}"
gunicorn_group: "{{ application_group }}"

gunicorn_module_app: conf.wsgi

gunicorn_num_workers: 3
gunicorn_max_requests: 0
gunicorn_timeout_seconds: 30
