# Generated by Django 2.0.1 on 2018-01-29 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=200, null=True)),
                ('host', models.TextField()),
                ('uri', models.TextField()),
                ('querystring', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('request_time', models.DurationField()),
            ],
        ),
    ]
