# Generated by Django 2.0.1 on 2018-04-17 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_registry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=200, null=True)),
                ('host', models.TextField()),
                ('uri', models.TextField()),
                ('querystring', models.TextField(blank=True, default='')),
                ('start_time', models.DateTimeField()),
                ('request_time', models.DecimalField(decimal_places=25, max_digits=30)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('user_agent', models.TextField()),
                ('api_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api_registry.KongApi')),
            ],
            options={
                'verbose_name': 'query',
                'verbose_name_plural': 'queries',
            },
        ),
    ]
