# Generated by Django 2.0.1 on 2018-02-01 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='querystring',
            field=models.TextField(blank=True, default=''),
        ),
    ]
