# Generated by Django 2.0.1 on 2018-04-19 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='token',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
