# Generated by Django 2.0.1 on 2018-08-21 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_query_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='x_source',
            field=models.TextField(default='', null=True),
        ),
    ]
