# Generated by Django 2.0.1 on 2018-03-15 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_auto_20180201_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='status_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
