# Generated by Django 2.0.1 on 2018-03-15 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_registry', '0012_remove_apidata_httplog2_endpoint'),
        ('analytics', '0003_query_status_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='api_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api_registry.ApiData'),
        ),
    ]
