# Generated by Django 2.0.1 on 2018-09-13 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_query_x_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='start_time',
            field=models.DateTimeField(db_index=True),
        ),
    ]
