# Generated by Django 2.0.1 on 2018-03-27 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_query_api_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='request_time',
            field=models.DecimalField(decimal_places=25, max_digits=30),
        ),
    ]
