# Generated by Django 2.0.1 on 2018-09-27 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_csvfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='CsvAnalyticsGeneratorTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('logs', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='csvfile',
            name='file',
            field=models.FileField(upload_to='media'),
        ),
    ]
