# Generated by Django 2.0.1 on 2018-10-17 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_auto_20180927_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleAnalyticsSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ga_id', models.CharField(blank=True, default='', max_length=100, verbose_name='Google analytics ID')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
