# Generated by Django 2.0.1 on 2019-01-02 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0010_indicatormetricsrow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicatormetricsrow',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
