# Generated by Django 2.0.1 on 2019-01-14 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0011_auto_20190102_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatormetricsrow',
            name='total_users_last_180',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indicatormetricsrow',
            name='total_users_last_30',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indicatormetricsrow',
            name='total_users_last_90',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
