# Generated by Django 2.0.1 on 2019-01-28 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0013_csvcompressortask'),
    ]

    operations = [
        migrations.AddField(
            model_name='zipfile',
            name='api_name',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
