# Generated by Django 2.0.1 on 2019-02-04 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0014_zipfile_api_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CsvCompressorAndRemoverTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('logs', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
