# Generated by Django 2.0.12 on 2019-08-21 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0015_csvcompressorandremovertask'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='csvcompressorandremovertask',
            options={'verbose_name': 'Csv remover task'},
        ),
        migrations.AddField(
            model_name='query',
            name='referer',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
