# Generated by Django 2.0.12 on 2019-09-06 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0016_auto_20190821_1148'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApiSessionSettings',
        ),
        migrations.AddField(
            model_name='googleanalyticssettings',
            name='max_timeout',
            field=models.IntegerField(default=10, verbose_name='session timeout in minutes'),
        ),
    ]
